Timestamp: 12/22/2020 8:46:12 PM

Message: HandlingInstanceID: 41dc4a56-9ba5-4f26-b9dc-f2067f0d31fd
An exception of type 'Minio.Exceptions.ConnectionException' occurred and was caught.
------------------------------------------------------------------------------------
12/22/2020 20:46:12
Type : Minio.Exceptions.ConnectionException, Minio, Version=3.1.13.0, Culture=neutral, PublicKeyToken=348239ebd7debb4c
Message : MinIO API responded with message=Connection error: Unable to connect to the remote server. Status code=0, response=Unable to connect to the remote server, content=
Source : Minio
Help link : 
ServerMessage : Connection error: Unable to connect to the remote server
ServerResponse : RestSharp.RestResponse
Response : 
XmlError : 
Data : System.Collections.ListDictionaryInternal
TargetSite : Void ParseErrorNoContent(RestSharp.IRestResponse)
HResult : -2146233088
Stack Trace :    at Minio.MinioClient.ParseErrorNoContent(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 445
   at Minio.MinioClient.ParseError(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 426
   at Minio.MinioClient.<>c.<.ctor>b__84_0(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 81
   at Minio.MinioClient.HandleIfErrorResponse(IRestResponse response, IEnumerable`1 handlers, DateTime startTime) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 604
   at Minio.MinioClient.<ExecuteTaskCoreAsync>d__91.MoveNext() in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 404
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.BucketRegionCache.<Update>d__9.MoveNext() in /q/.q/sources/minio-dotnet/Minio/BucketRegionCache.cs:line 104
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.MinioClient.<GetRegion>d__80.MoveNext() in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 134
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.MinioClient.<CreateRequest>d__81.MoveNext() in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 167
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.MinioClient.<BucketExistsAsync>d__2.MoveNext() in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/BucketOperations.cs:line 124
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at IntellaLend.MinIOWrapper.ImageMinIOWrapper.CheckFileExists(Int64 loanID) in D:\Prakash\GitHub\ILProduct\IntellaLendBlocks\IntellaLend.MinIOWrapper\MinIOWrapper.cs:line 237
   at IntellaLend.EntityDataHandler.LoanDataAccess.CheckLoanPDFExists(Int64 LoanID) in D:\Prakash\GitHub\ILProduct\IntellaLendAPI\IntellaLend.LoanData\LoanDataAccess.cs:line 1372
   at IntellaLend.CommonServices.LoanService.CheckLoanPDFExists(Int64 LoanID) in D:\Prakash\GitHub\ILProduct\IntellaLendAPI\IntellaLend.Services\LoanService\LoanService.cs:line 105
   at IntellaLendAPI.Controllers.LoanController.CheckLoanPDFExists(LoanRequest loan) in D:\Prakash\GitHub\ILProduct\IntellaLendAPI\IntellaLendAPI\Controllers\LoanController.cs:line 840

Additional Info:

MachineName : MTS0091
TimeStamp : 12/22/2020 3:16:12 PM
FullName : Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
AppDomainName : /LM/W3SVC/2/ROOT-1-132531234307358378
ThreadIdentity : APIResponse
WindowsIdentity : MTS0091\mtsuser


Category: General
EventID: 9000
Priority: 0
Severity: ErrorTitile: Enterprise Library Exception Handling
----------------------------------------
Timestamp: 12/22/2020 8:48:24 PM

Message: HandlingInstanceID: 84f91319-89c2-4033-b184-fe926c01c55e
An exception of type 'Minio.Exceptions.ConnectionException' occurred and was caught.
------------------------------------------------------------------------------------
12/22/2020 20:48:24
Type : Minio.Exceptions.ConnectionException, Minio, Version=3.1.13.0, Culture=neutral, PublicKeyToken=348239ebd7debb4c
Message : MinIO API responded with message=Connection error: Unable to connect to the remote server. Status code=0, response=Unable to connect to the remote server, content=
Source : Minio
Help link : 
ServerMessage : Connection error: Unable to connect to the remote server
ServerResponse : RestSharp.RestResponse
Response : 
XmlError : 
Data : System.Collections.ListDictionaryInternal
TargetSite : Void ParseErrorNoContent(RestSharp.IRestResponse)
HResult : -2146233088
Stack Trace :    at Minio.MinioClient.ParseErrorNoContent(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 445
   at Minio.MinioClient.ParseError(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 426
   at Minio.MinioClient.<>c.<.ctor>b__84_0(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 81
   at Minio.MinioClient.HandleIfErrorResponse(IRestResponse response, IEnumerable`1 handlers, DateTime startTime) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 604
   at Minio.MinioClient.<ExecuteTaskCoreAsync>d__91.MoveNext() in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 404
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.BucketRegionCache.<Update>d__9.MoveNext() in /q/.q/sources/minio-dotnet/Minio/BucketRegionCache.cs:line 104
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.MinioClient.<GetRegion>d__80.MoveNext() in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 134
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.MinioClient.<CreateRequest>d__81.MoveNext() in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 167
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.MinioClient.<BucketExistsAsync>d__2.MoveNext() in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/BucketOperations.cs:line 124
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at IntellaLend.MinIOWrapper.ImageMinIOWrapper.CheckFileExists(Int64 loanID) in D:\Prakash\GitHub\ILProduct\IntellaLendBlocks\IntellaLend.MinIOWrapper\MinIOWrapper.cs:line 237
   at IntellaLend.EntityDataHandler.LoanDataAccess.CheckLoanPDFExists(Int64 LoanID) in D:\Prakash\GitHub\ILProduct\IntellaLendAPI\IntellaLend.LoanData\LoanDataAccess.cs:line 1372
   at IntellaLend.CommonServices.LoanService.CheckLoanPDFExists(Int64 LoanID) in D:\Prakash\GitHub\ILProduct\IntellaLendAPI\IntellaLend.Services\LoanService\LoanService.cs:line 105
   at IntellaLendAPI.Controllers.LoanController.CheckLoanPDFExists(LoanRequest loan) in D:\Prakash\GitHub\ILProduct\IntellaLendAPI\IntellaLendAPI\Controllers\LoanController.cs:line 840

Additional Info:

MachineName : MTS0091
TimeStamp : 12/22/2020 3:18:24 PM
FullName : Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
AppDomainName : /LM/W3SVC/2/ROOT-1-132531234307358378
ThreadIdentity : APIResponse
WindowsIdentity : MTS0091\mtsuser


Category: General
EventID: 9000
Priority: 0
Severity: ErrorTitile: Enterprise Library Exception Handling
----------------------------------------
Timestamp: 12/22/2020 8:53:53 PM

Message: HandlingInstanceID: c2ababb3-ed5a-464c-8b5e-e991281280bd
An exception of type 'Minio.Exceptions.ConnectionException' occurred and was caught.
------------------------------------------------------------------------------------
12/22/2020 20:53:53
Type : Minio.Exceptions.ConnectionException, Minio, Version=3.1.13.0, Culture=neutral, PublicKeyToken=348239ebd7debb4c
Message : MinIO API responded with message=Connection error: Unable to connect to the remote server. Status code=0, response=Unable to connect to the remote server, content=
Source : Minio
Help link : 
ServerMessage : Connection error: Unable to connect to the remote server
ServerResponse : RestSharp.RestResponse
Response : 
XmlError : 
Data : System.Collections.ListDictionaryInternal
TargetSite : Void ParseErrorNoContent(RestSharp.IRestResponse)
HResult : -2146233088
Stack Trace :    at Minio.MinioClient.ParseErrorNoContent(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 445
   at Minio.MinioClient.ParseError(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 426
   at Minio.MinioClient.<>c.<.ctor>b__84_0(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 81
   at Minio.MinioClient.HandleIfErrorResponse(IRestResponse response, IEnumerable`1 handlers, DateTime startTime) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 604
   at Minio.MinioClient.<ExecuteTaskCoreAsync>d__91.MoveNext() in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 404
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.BucketRegionCache.<Update>d__9.MoveNext() in /q/.q/sources/minio-dotnet/Minio/BucketRegionCache.cs:line 104
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.MinioClient.<GetRegion>d__80.MoveNext() in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 134
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.MinioClient.<CreateRequest>d__81.MoveNext() in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 167
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.MinioClient.<BucketExistsAsync>d__2.MoveNext() in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/BucketOperations.cs:line 124
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at IntellaLend.MinIOWrapper.ImageMinIOWrapper.CheckFileExists(Int64 loanID) in D:\Prakash\GitHub\ILProduct\IntellaLendBlocks\IntellaLend.MinIOWrapper\MinIOWrapper.cs:line 237
   at IntellaLend.EntityDataHandler.LoanDataAccess.CheckLoanPDFExists(Int64 LoanID) in D:\Prakash\GitHub\ILProduct\IntellaLendAPI\IntellaLend.LoanData\LoanDataAccess.cs:line 1372
   at IntellaLend.CommonServices.LoanService.CheckLoanPDFExists(Int64 LoanID) in D:\Prakash\GitHub\ILProduct\IntellaLendAPI\IntellaLend.Services\LoanService\LoanService.cs:line 105
   at IntellaLendAPI.Controllers.LoanController.CheckLoanPDFExists(LoanRequest loan) in D:\Prakash\GitHub\ILProduct\IntellaLendAPI\IntellaLendAPI\Controllers\LoanController.cs:line 840

Additional Info:

MachineName : MTS0091
TimeStamp : 12/22/2020 3:23:53 PM
FullName : Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
AppDomainName : /LM/W3SVC/2/ROOT-1-132531234307358378
ThreadIdentity : APIResponse
WindowsIdentity : MTS0091\mtsuser


Category: General
EventID: 9000
Priority: 0
Severity: ErrorTitile: Enterprise Library Exception Handling
----------------------------------------
Timestamp: 12/22/2020 8:59:45 PM

Message: HandlingInstanceID: 39435d4e-24a3-4150-8207-618834d94254
An exception of type 'Minio.Exceptions.ConnectionException' occurred and was caught.
------------------------------------------------------------------------------------
12/22/2020 20:59:45
Type : Minio.Exceptions.ConnectionException, Minio, Version=3.1.13.0, Culture=neutral, PublicKeyToken=348239ebd7debb4c
Message : MinIO API responded with message=Connection error: Unable to connect to the remote server. Status code=0, response=Unable to connect to the remote server, content=
Source : Minio
Help link : 
ServerMessage : Connection error: Unable to connect to the remote server
ServerResponse : RestSharp.RestResponse
Response : 
XmlError : 
Data : System.Collections.ListDictionaryInternal
TargetSite : Void ParseErrorNoContent(RestSharp.IRestResponse)
HResult : -2146233088
Stack Trace :    at Minio.MinioClient.ParseErrorNoContent(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 445
   at Minio.MinioClient.ParseError(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 426
   at Minio.MinioClient.<>c.<.ctor>b__84_0(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 81
   at Minio.MinioClient.HandleIfErrorResponse(IRestResponse response, IEnumerable`1 handlers, DateTime startTime) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 604
   at Minio.MinioClient.<ExecuteTaskCoreAsync>d__91.MoveNext() in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 404
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.BucketRegionCache.<Update>d__9.MoveNext() in /q/.q/sources/minio-dotnet/Minio/BucketRegionCache.cs:line 104
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.MinioClient.<GetRegion>d__80.MoveNext() in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 134
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.MinioClient.<CreateRequest>d__81.MoveNext() in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 167
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.MinioClient.<BucketExistsAsync>d__2.MoveNext() in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/BucketOperations.cs:line 124
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at IntellaLend.MinIOWrapper.ImageMinIOWrapper.CheckFileExists(Int64 loanID) in D:\Prakash\GitHub\ILProduct\IntellaLendBlocks\IntellaLend.MinIOWrapper\MinIOWrapper.cs:line 237
   at IntellaLend.EntityDataHandler.LoanDataAccess.CheckLoanPDFExists(Int64 LoanID) in D:\Prakash\GitHub\ILProduct\IntellaLendAPI\IntellaLend.LoanData\LoanDataAccess.cs:line 1372
   at IntellaLend.CommonServices.LoanService.CheckLoanPDFExists(Int64 LoanID) in D:\Prakash\GitHub\ILProduct\IntellaLendAPI\IntellaLend.Services\LoanService\LoanService.cs:line 105
   at IntellaLendAPI.Controllers.LoanController.CheckLoanPDFExists(LoanRequest loan) in D:\Prakash\GitHub\ILProduct\IntellaLendAPI\IntellaLendAPI\Controllers\LoanController.cs:line 840

Additional Info:

MachineName : MTS0091
TimeStamp : 12/22/2020 3:29:45 PM
FullName : Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
AppDomainName : /LM/W3SVC/2/ROOT-1-132531234307358378
ThreadIdentity : APIResponse
WindowsIdentity : MTS0091\mtsuser


Category: General
EventID: 9000
Priority: 0
Severity: ErrorTitile: Enterprise Library Exception Handling
----------------------------------------
Timestamp: 12/22/2020 9:06:25 PM

Message: HandlingInstanceID: e8cdc252-1980-403d-8f80-d94026c6cab9
An exception of type 'Minio.Exceptions.ConnectionException' occurred and was caught.
------------------------------------------------------------------------------------
12/22/2020 21:06:25
Type : Minio.Exceptions.ConnectionException, Minio, Version=3.1.13.0, Culture=neutral, PublicKeyToken=348239ebd7debb4c
Message : MinIO API responded with message=Connection error: Unable to connect to the remote server. Status code=0, response=Unable to connect to the remote server, content=
Source : Minio
Help link : 
ServerMessage : Connection error: Unable to connect to the remote server
ServerResponse : RestSharp.RestResponse
Response : 
XmlError : 
Data : System.Collections.ListDictionaryInternal
TargetSite : Void ParseErrorNoContent(RestSharp.IRestResponse)
HResult : -2146233088
Stack Trace :    at Minio.MinioClient.ParseErrorNoContent(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 445
   at Minio.MinioClient.ParseError(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 426
   at Minio.MinioClient.<>c.<.ctor>b__84_0(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 81
   at Minio.MinioClient.HandleIfErrorResponse(IRestResponse response, IEnumerable`1 handlers, DateTime startTime) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 604
   at Minio.MinioClient.<ExecuteTaskCoreAsync>d__91.MoveNext() in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 404
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.BucketRegionCache.<Update>d__9.MoveNext() in /q/.q/sources/minio-dotnet/Minio/BucketRegionCache.cs:line 104
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.MinioClient.<GetRegion>d__80.MoveNext() in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 134
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.MinioClient.<CreateRequest>d__81.MoveNext() in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 167
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.MinioClient.<BucketExistsAsync>d__2.MoveNext() in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/BucketOperations.cs:line 124
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at IntellaLend.MinIOWrapper.ImageMinIOWrapper.CheckFileExists(Int64 loanID) in D:\Prakash\GitHub\ILProduct\IntellaLendBlocks\IntellaLend.MinIOWrapper\MinIOWrapper.cs:line 237
   at IntellaLend.EntityDataHandler.LoanDataAccess.CheckLoanPDFExists(Int64 LoanID) in D:\Prakash\GitHub\ILProduct\IntellaLendAPI\IntellaLend.LoanData\LoanDataAccess.cs:line 1372
   at IntellaLend.CommonServices.LoanService.CheckLoanPDFExists(Int64 LoanID) in D:\Prakash\GitHub\ILProduct\IntellaLendAPI\IntellaLend.Services\LoanService\LoanService.cs:line 105
   at IntellaLendAPI.Controllers.LoanController.CheckLoanPDFExists(LoanRequest loan) in D:\Prakash\GitHub\ILProduct\IntellaLendAPI\IntellaLendAPI\Controllers\LoanController.cs:line 840

Additional Info:

MachineName : MTS0091
TimeStamp : 12/22/2020 3:36:25 PM
FullName : Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
AppDomainName : /LM/W3SVC/2/ROOT-1-132531234307358378
ThreadIdentity : APIResponse
WindowsIdentity : MTS0091\mtsuser


Category: General
EventID: 9000
Priority: 0
Severity: ErrorTitile: Enterprise Library Exception Handling
----------------------------------------
Timestamp: 12/22/2020 9:09:28 PM

Message: HandlingInstanceID: 19c5ba7a-07f9-46d5-957c-4f75eeb5edbc
An exception of type 'Minio.Exceptions.ConnectionException' occurred and was caught.
------------------------------------------------------------------------------------
12/22/2020 21:09:28
Type : Minio.Exceptions.ConnectionException, Minio, Version=3.1.13.0, Culture=neutral, PublicKeyToken=348239ebd7debb4c
Message : MinIO API responded with message=Connection error: Unable to connect to the remote server. Status code=0, response=Unable to connect to the remote server, content=
Source : Minio
Help link : 
ServerMessage : Connection error: Unable to connect to the remote server
ServerResponse : RestSharp.RestResponse
Response : 
XmlError : 
Data : System.Collections.ListDictionaryInternal
TargetSite : Void ParseErrorNoContent(RestSharp.IRestResponse)
HResult : -2146233088
Stack Trace :    at Minio.MinioClient.ParseErrorNoContent(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 445
   at Minio.MinioClient.ParseError(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 426
   at Minio.MinioClient.<>c.<.ctor>b__84_0(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 81
   at Minio.MinioClient.HandleIfErrorResponse(IRestResponse response, IEnumerable`1 handlers, DateTime startTime) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 604
   at Minio.MinioClient.<ExecuteTaskCoreAsync>d__91.MoveNext() in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 404
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.BucketRegionCache.<Update>d__9.MoveNext() in /q/.q/sources/minio-dotnet/Minio/BucketRegionCache.cs:line 104
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.MinioClient.<GetRegion>d__80.MoveNext() in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 134
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.MinioClient.<CreateRequest>d__81.MoveNext() in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 167
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.MinioClient.<BucketExistsAsync>d__2.MoveNext() in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/BucketOperations.cs:line 124
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at IntellaLend.MinIOWrapper.ImageMinIOWrapper.CheckFileExists(Int64 loanID) in D:\Prakash\GitHub\ILProduct\IntellaLendBlocks\IntellaLend.MinIOWrapper\MinIOWrapper.cs:line 237
   at IntellaLend.EntityDataHandler.LoanDataAccess.CheckLoanPDFExists(Int64 LoanID) in D:\Prakash\GitHub\ILProduct\IntellaLendAPI\IntellaLend.LoanData\LoanDataAccess.cs:line 1372
   at IntellaLend.CommonServices.LoanService.CheckLoanPDFExists(Int64 LoanID) in D:\Prakash\GitHub\ILProduct\IntellaLendAPI\IntellaLend.Services\LoanService\LoanService.cs:line 105
   at IntellaLendAPI.Controllers.LoanController.CheckLoanPDFExists(LoanRequest loan) in D:\Prakash\GitHub\ILProduct\IntellaLendAPI\IntellaLendAPI\Controllers\LoanController.cs:line 840

Additional Info:

MachineName : MTS0091
TimeStamp : 12/22/2020 3:39:28 PM
FullName : Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
AppDomainName : /LM/W3SVC/2/ROOT-1-132531234307358378
ThreadIdentity : APIResponse
WindowsIdentity : MTS0091\mtsuser


Category: General
EventID: 9000
Priority: 0
Severity: ErrorTitile: Enterprise Library Exception Handling
----------------------------------------
Timestamp: 12/22/2020 9:13:50 PM

Message: HandlingInstanceID: 7ebd12ae-acee-4e21-a66b-45f70501e974
An exception of type 'Minio.Exceptions.ConnectionException' occurred and was caught.
------------------------------------------------------------------------------------
12/22/2020 21:13:50
Type : Minio.Exceptions.ConnectionException, Minio, Version=3.1.13.0, Culture=neutral, PublicKeyToken=348239ebd7debb4c
Message : MinIO API responded with message=Connection error: Unable to connect to the remote server. Status code=0, response=Unable to connect to the remote server, content=
Source : Minio
Help link : 
ServerMessage : Connection error: Unable to connect to the remote server
ServerResponse : RestSharp.RestResponse
Response : 
XmlError : 
Data : System.Collections.ListDictionaryInternal
TargetSite : Void ParseErrorNoContent(RestSharp.IRestResponse)
HResult : -2146233088
Stack Trace :    at Minio.MinioClient.ParseErrorNoContent(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 445
   at Minio.MinioClient.ParseError(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 426
   at Minio.MinioClient.<>c.<.ctor>b__84_0(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 81
   at Minio.MinioClient.HandleIfErrorResponse(IRestResponse response, IEnumerable`1 handlers, DateTime startTime) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 604
   at Minio.MinioClient.<ExecuteTaskCoreAsync>d__91.MoveNext() in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 404
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.BucketRegionCache.<Update>d__9.MoveNext() in /q/.q/sources/minio-dotnet/Minio/BucketRegionCache.cs:line 104
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.MinioClient.<GetRegion>d__80.MoveNext() in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 134
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.MinioClient.<CreateRequest>d__81.MoveNext() in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 167
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.MinioClient.<BucketExistsAsync>d__2.MoveNext() in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/BucketOperations.cs:line 124
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at IntellaLend.MinIOWrapper.ImageMinIOWrapper.CheckFileExists(Int64 loanID) in D:\Prakash\GitHub\ILProduct\IntellaLendBlocks\IntellaLend.MinIOWrapper\MinIOWrapper.cs:line 237
   at IntellaLend.EntityDataHandler.LoanDataAccess.CheckLoanPDFExists(Int64 LoanID) in D:\Prakash\GitHub\ILProduct\IntellaLendAPI\IntellaLend.LoanData\LoanDataAccess.cs:line 1372
   at IntellaLend.CommonServices.LoanService.CheckLoanPDFExists(Int64 LoanID) in D:\Prakash\GitHub\ILProduct\IntellaLendAPI\IntellaLend.Services\LoanService\LoanService.cs:line 105
   at IntellaLendAPI.Controllers.LoanController.CheckLoanPDFExists(LoanRequest loan) in D:\Prakash\GitHub\ILProduct\IntellaLendAPI\IntellaLendAPI\Controllers\LoanController.cs:line 840

Additional Info:

MachineName : MTS0091
TimeStamp : 12/22/2020 3:43:50 PM
FullName : Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
AppDomainName : /LM/W3SVC/2/ROOT-1-132531234307358378
ThreadIdentity : APIResponse
WindowsIdentity : MTS0091\mtsuser


Category: General
EventID: 9000
Priority: 0
Severity: ErrorTitile: Enterprise Library Exception Handling
----------------------------------------
Timestamp: 12/22/2020 9:16:05 PM

Message: HandlingInstanceID: 6275852a-df04-46b8-afd3-b388a4f9a2a2
An exception of type 'Minio.Exceptions.ConnectionException' occurred and was caught.
------------------------------------------------------------------------------------
12/22/2020 21:16:05
Type : Minio.Exceptions.ConnectionException, Minio, Version=3.1.13.0, Culture=neutral, PublicKeyToken=348239ebd7debb4c
Message : MinIO API responded with message=Connection error: Unable to connect to the remote server. Status code=0, response=Unable to connect to the remote server, content=
Source : Minio
Help link : 
ServerMessage : Connection error: Unable to connect to the remote server
ServerResponse : RestSharp.RestResponse
Response : 
XmlError : 
Data : System.Collections.ListDictionaryInternal
TargetSite : Void ParseErrorNoContent(RestSharp.IRestResponse)
HResult : -2146233088
Stack Trace :    at Minio.MinioClient.ParseErrorNoContent(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 445
   at Minio.MinioClient.ParseError(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 426
   at Minio.MinioClient.<>c.<.ctor>b__84_0(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 81
   at Minio.MinioClient.HandleIfErrorResponse(IRestResponse response, IEnumerable`1 handlers, DateTime startTime) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 604
   at Minio.MinioClient.<ExecuteTaskCoreAsync>d__91.MoveNext() in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 404
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.BucketRegionCache.<Update>d__9.MoveNext() in /q/.q/sources/minio-dotnet/Minio/BucketRegionCache.cs:line 104
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.MinioClient.<GetRegion>d__80.MoveNext() in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 134
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.MinioClient.<CreateRequest>d__81.MoveNext() in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 167
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.MinioClient.<BucketExistsAsync>d__2.MoveNext() in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/BucketOperations.cs:line 124
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at IntellaLend.MinIOWrapper.ImageMinIOWrapper.CheckFileExists(Int64 loanID) in D:\Prakash\GitHub\ILProduct\IntellaLendBlocks\IntellaLend.MinIOWrapper\MinIOWrapper.cs:line 237
   at IntellaLend.EntityDataHandler.LoanDataAccess.CheckLoanPDFExists(Int64 LoanID) in D:\Prakash\GitHub\ILProduct\IntellaLendAPI\IntellaLend.LoanData\LoanDataAccess.cs:line 1372
   at IntellaLend.CommonServices.LoanService.CheckLoanPDFExists(Int64 LoanID) in D:\Prakash\GitHub\ILProduct\IntellaLendAPI\IntellaLend.Services\LoanService\LoanService.cs:line 105
   at IntellaLendAPI.Controllers.LoanController.CheckLoanPDFExists(LoanRequest loan) in D:\Prakash\GitHub\ILProduct\IntellaLendAPI\IntellaLendAPI\Controllers\LoanController.cs:line 840

Additional Info:

MachineName : MTS0091
TimeStamp : 12/22/2020 3:46:05 PM
FullName : Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
AppDomainName : /LM/W3SVC/2/ROOT-1-132531234307358378
ThreadIdentity : APIResponse
WindowsIdentity : MTS0091\mtsuser


Category: General
EventID: 9000
Priority: 0
Severity: ErrorTitile: Enterprise Library Exception Handling
----------------------------------------
Timestamp: 12/22/2020 9:18:38 PM

Message: HandlingInstanceID: 1839cfa7-57a5-4d9f-a09d-88be2b9e3ba5
An exception of type 'Minio.Exceptions.ConnectionException' occurred and was caught.
------------------------------------------------------------------------------------
12/22/2020 21:18:38
Type : Minio.Exceptions.ConnectionException, Minio, Version=3.1.13.0, Culture=neutral, PublicKeyToken=348239ebd7debb4c
Message : MinIO API responded with message=Connection error: Unable to connect to the remote server. Status code=0, response=Unable to connect to the remote server, content=
Source : Minio
Help link : 
ServerMessage : Connection error: Unable to connect to the remote server
ServerResponse : RestSharp.RestResponse
Response : 
XmlError : 
Data : System.Collections.ListDictionaryInternal
TargetSite : Void ParseErrorNoContent(RestSharp.IRestResponse)
HResult : -2146233088
Stack Trace :    at Minio.MinioClient.ParseErrorNoContent(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 445
   at Minio.MinioClient.ParseError(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 426
   at Minio.MinioClient.<>c.<.ctor>b__84_0(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 81
   at Minio.MinioClient.HandleIfErrorResponse(IRestResponse response, IEnumerable`1 handlers, DateTime startTime) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 604
   at Minio.MinioClient.<ExecuteTaskCoreAsync>d__91.MoveNext() in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 404
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.BucketRegionCache.<Update>d__9.MoveNext() in /q/.q/sources/minio-dotnet/Minio/BucketRegionCache.cs:line 104
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.MinioClient.<GetRegion>d__80.MoveNext() in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 134
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.MinioClient.<CreateRequest>d__81.MoveNext() in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 167
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.MinioClient.<BucketExistsAsync>d__2.MoveNext() in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/BucketOperations.cs:line 124
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at IntellaLend.MinIOWrapper.ImageMinIOWrapper.CheckFileExists(Int64 loanID) in D:\Prakash\GitHub\ILProduct\IntellaLendBlocks\IntellaLend.MinIOWrapper\MinIOWrapper.cs:line 237
   at IntellaLend.EntityDataHandler.LoanDataAccess.CheckLoanPDFExists(Int64 LoanID) in D:\Prakash\GitHub\ILProduct\IntellaLendAPI\IntellaLend.LoanData\LoanDataAccess.cs:line 1372
   at IntellaLend.CommonServices.LoanService.CheckLoanPDFExists(Int64 LoanID) in D:\Prakash\GitHub\ILProduct\IntellaLendAPI\IntellaLend.Services\LoanService\LoanService.cs:line 105
   at IntellaLendAPI.Controllers.LoanController.CheckLoanPDFExists(LoanRequest loan) in D:\Prakash\GitHub\ILProduct\IntellaLendAPI\IntellaLendAPI\Controllers\LoanController.cs:line 840

Additional Info:

MachineName : MTS0091
TimeStamp : 12/22/2020 3:48:38 PM
FullName : Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
AppDomainName : /LM/W3SVC/2/ROOT-1-132531234307358378
ThreadIdentity : APIResponse
WindowsIdentity : MTS0091\mtsuser


Category: General
EventID: 9000
Priority: 0
Severity: ErrorTitile: Enterprise Library Exception Handling
----------------------------------------
Timestamp: 12/22/2020 9:20:16 PM

Message: HandlingInstanceID: 51d1a64e-3e6d-4ba9-9f09-4706d15d606e
An exception of type 'Minio.Exceptions.ConnectionException' occurred and was caught.
------------------------------------------------------------------------------------
12/22/2020 21:20:16
Type : Minio.Exceptions.ConnectionException, Minio, Version=3.1.13.0, Culture=neutral, PublicKeyToken=348239ebd7debb4c
Message : MinIO API responded with message=Connection error: Unable to connect to the remote server. Status code=0, response=Unable to connect to the remote server, content=
Source : Minio
Help link : 
ServerMessage : Connection error: Unable to connect to the remote server
ServerResponse : RestSharp.RestResponse
Response : 
XmlError : 
Data : System.Collections.ListDictionaryInternal
TargetSite : Void ParseErrorNoContent(RestSharp.IRestResponse)
HResult : -2146233088
Stack Trace :    at Minio.MinioClient.ParseErrorNoContent(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 445
   at Minio.MinioClient.ParseError(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 426
   at Minio.MinioClient.<>c.<.ctor>b__84_0(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 81
   at Minio.MinioClient.HandleIfErrorResponse(IRestResponse response, IEnumerable`1 handlers, DateTime startTime) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 604
   at Minio.MinioClient.<ExecuteTaskCoreAsync>d__91.MoveNext() in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 404
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.BucketRegionCache.<Update>d__9.MoveNext() in /q/.q/sources/minio-dotnet/Minio/BucketRegionCache.cs:line 104
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.MinioClient.<GetRegion>d__80.MoveNext() in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 134
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.MinioClient.<CreateRequest>d__81.MoveNext() in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 167
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.MinioClient.<BucketExistsAsync>d__2.MoveNext() in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/BucketOperations.cs:line 124
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at IntellaLend.MinIOWrapper.ImageMinIOWrapper.CheckFileExists(Int64 loanID) in D:\Prakash\GitHub\ILProduct\IntellaLendBlocks\IntellaLend.MinIOWrapper\MinIOWrapper.cs:line 237
   at IntellaLend.EntityDataHandler.LoanDataAccess.CheckLoanPDFExists(Int64 LoanID) in D:\Prakash\GitHub\ILProduct\IntellaLendAPI\IntellaLend.LoanData\LoanDataAccess.cs:line 1372
   at IntellaLend.CommonServices.LoanService.CheckLoanPDFExists(Int64 LoanID) in D:\Prakash\GitHub\ILProduct\IntellaLendAPI\IntellaLend.Services\LoanService\LoanService.cs:line 105
   at IntellaLendAPI.Controllers.LoanController.CheckLoanPDFExists(LoanRequest loan) in D:\Prakash\GitHub\ILProduct\IntellaLendAPI\IntellaLendAPI\Controllers\LoanController.cs:line 840

Additional Info:

MachineName : MTS0091
TimeStamp : 12/22/2020 3:50:16 PM
FullName : Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
AppDomainName : /LM/W3SVC/2/ROOT-1-132531234307358378
ThreadIdentity : APIResponse
WindowsIdentity : MTS0091\mtsuser


Category: General
EventID: 9000
Priority: 0
Severity: ErrorTitile: Enterprise Library Exception Handling
----------------------------------------
Timestamp: 12/22/2020 9:21:23 PM

Message: HandlingInstanceID: 6951859b-ad80-4c1e-a07d-e42bf5eeca3f
An exception of type 'Minio.Exceptions.ConnectionException' occurred and was caught.
------------------------------------------------------------------------------------
12/22/2020 21:21:23
Type : Minio.Exceptions.ConnectionException, Minio, Version=3.1.13.0, Culture=neutral, PublicKeyToken=348239ebd7debb4c
Message : MinIO API responded with message=Connection error: Unable to connect to the remote server. Status code=0, response=Unable to connect to the remote server, content=
Source : Minio
Help link : 
ServerMessage : Connection error: Unable to connect to the remote server
ServerResponse : RestSharp.RestResponse
Response : 
XmlError : 
Data : System.Collections.ListDictionaryInternal
TargetSite : Void ParseErrorNoContent(RestSharp.IRestResponse)
HResult : -2146233088
Stack Trace :    at Minio.MinioClient.ParseErrorNoContent(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 445
   at Minio.MinioClient.ParseError(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 426
   at Minio.MinioClient.<>c.<.ctor>b__84_0(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 81
   at Minio.MinioClient.HandleIfErrorResponse(IRestResponse response, IEnumerable`1 handlers, DateTime startTime) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 604
   at Minio.MinioClient.<ExecuteTaskCoreAsync>d__91.MoveNext() in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 404
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.BucketRegionCache.<Update>d__9.MoveNext() in /q/.q/sources/minio-dotnet/Minio/BucketRegionCache.cs:line 104
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.MinioClient.<GetRegion>d__80.MoveNext() in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 134
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.MinioClient.<CreateRequest>d__81.MoveNext() in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 167
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.MinioClient.<BucketExistsAsync>d__2.MoveNext() in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/BucketOperations.cs:line 124
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at IntellaLend.MinIOWrapper.ImageMinIOWrapper.CheckFileExists(Int64 loanID) in D:\Prakash\GitHub\ILProduct\IntellaLendBlocks\IntellaLend.MinIOWrapper\MinIOWrapper.cs:line 237
   at IntellaLend.EntityDataHandler.LoanDataAccess.CheckLoanPDFExists(Int64 LoanID) in D:\Prakash\GitHub\ILProduct\IntellaLendAPI\IntellaLend.LoanData\LoanDataAccess.cs:line 1372
   at IntellaLend.CommonServices.LoanService.CheckLoanPDFExists(Int64 LoanID) in D:\Prakash\GitHub\ILProduct\IntellaLendAPI\IntellaLend.Services\LoanService\LoanService.cs:line 105
   at IntellaLendAPI.Controllers.LoanController.CheckLoanPDFExists(LoanRequest loan) in D:\Prakash\GitHub\ILProduct\IntellaLendAPI\IntellaLendAPI\Controllers\LoanController.cs:line 840

Additional Info:

MachineName : MTS0091
TimeStamp : 12/22/2020 3:51:23 PM
FullName : Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
AppDomainName : /LM/W3SVC/2/ROOT-1-132531234307358378
ThreadIdentity : APIResponse
WindowsIdentity : MTS0091\mtsuser


Category: General
EventID: 9000
Priority: 0
Severity: ErrorTitile: Enterprise Library Exception Handling
----------------------------------------
Timestamp: 12/22/2020 9:23:16 PM

Message: HandlingInstanceID: 7faab31f-c3ef-4660-b3cf-1ca0804e2953
An exception of type 'Minio.Exceptions.ConnectionException' occurred and was caught.
------------------------------------------------------------------------------------
12/22/2020 21:23:16
Type : Minio.Exceptions.ConnectionException, Minio, Version=3.1.13.0, Culture=neutral, PublicKeyToken=348239ebd7debb4c
Message : MinIO API responded with message=Connection error: Unable to connect to the remote server. Status code=0, response=Unable to connect to the remote server, content=
Source : Minio
Help link : 
ServerMessage : Connection error: Unable to connect to the remote server
ServerResponse : RestSharp.RestResponse
Response : 
XmlError : 
Data : System.Collections.ListDictionaryInternal
TargetSite : Void ParseErrorNoContent(RestSharp.IRestResponse)
HResult : -2146233088
Stack Trace :    at Minio.MinioClient.ParseErrorNoContent(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 445
   at Minio.MinioClient.ParseError(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 426
   at Minio.MinioClient.<>c.<.ctor>b__84_0(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 81
   at Minio.MinioClient.HandleIfErrorResponse(IRestResponse response, IEnumerable`1 handlers, DateTime startTime) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 604
   at Minio.MinioClient.<ExecuteTaskCoreAsync>d__91.MoveNext() in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 404
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.BucketRegionCache.<Update>d__9.MoveNext() in /q/.q/sources/minio-dotnet/Minio/BucketRegionCache.cs:line 104
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.MinioClient.<GetRegion>d__80.MoveNext() in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 134
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.MinioClient.<CreateRequest>d__81.MoveNext() in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 167
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.MinioClient.<BucketExistsAsync>d__2.MoveNext() in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/BucketOperations.cs:line 124
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at IntellaLend.MinIOWrapper.ImageMinIOWrapper.CheckFileExists(Int64 loanID) in D:\Prakash\GitHub\ILProduct\IntellaLendBlocks\IntellaLend.MinIOWrapper\MinIOWrapper.cs:line 237
   at IntellaLend.EntityDataHandler.LoanDataAccess.CheckLoanPDFExists(Int64 LoanID) in D:\Prakash\GitHub\ILProduct\IntellaLendAPI\IntellaLend.LoanData\LoanDataAccess.cs:line 1372
   at IntellaLend.CommonServices.LoanService.CheckLoanPDFExists(Int64 LoanID) in D:\Prakash\GitHub\ILProduct\IntellaLendAPI\IntellaLend.Services\LoanService\LoanService.cs:line 105
   at IntellaLendAPI.Controllers.LoanController.CheckLoanPDFExists(LoanRequest loan) in D:\Prakash\GitHub\ILProduct\IntellaLendAPI\IntellaLendAPI\Controllers\LoanController.cs:line 840

Additional Info:

MachineName : MTS0091
TimeStamp : 12/22/2020 3:53:16 PM
FullName : Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
AppDomainName : /LM/W3SVC/2/ROOT-1-132531234307358378
ThreadIdentity : APIResponse
WindowsIdentity : MTS0091\mtsuser


Category: General
EventID: 9000
Priority: 0
Severity: ErrorTitile: Enterprise Library Exception Handling
----------------------------------------
Timestamp: 12/22/2020 9:24:13 PM

Message: HandlingInstanceID: c4726f1c-dc54-45c3-aacc-baf1dbdac162
An exception of type 'Minio.Exceptions.ConnectionException' occurred and was caught.
------------------------------------------------------------------------------------
12/22/2020 21:24:13
Type : Minio.Exceptions.ConnectionException, Minio, Version=3.1.13.0, Culture=neutral, PublicKeyToken=348239ebd7debb4c
Message : MinIO API responded with message=Connection error: Unable to connect to the remote server. Status code=0, response=Unable to connect to the remote server, content=
Source : Minio
Help link : 
ServerMessage : Connection error: Unable to connect to the remote server
ServerResponse : RestSharp.RestResponse
Response : 
XmlError : 
Data : System.Collections.ListDictionaryInternal
TargetSite : Void ParseErrorNoContent(RestSharp.IRestResponse)
HResult : -2146233088
Stack Trace :    at Minio.MinioClient.ParseErrorNoContent(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 445
   at Minio.MinioClient.ParseError(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 426
   at Minio.MinioClient.<>c.<.ctor>b__84_0(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 81
   at Minio.MinioClient.HandleIfErrorResponse(IRestResponse response, IEnumerable`1 handlers, DateTime startTime) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 604
   at Minio.MinioClient.<ExecuteTaskCoreAsync>d__91.MoveNext() in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 404
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.BucketRegionCache.<Update>d__9.MoveNext() in /q/.q/sources/minio-dotnet/Minio/BucketRegionCache.cs:line 104
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.MinioClient.<GetRegion>d__80.MoveNext() in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 134
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.MinioClient.<CreateRequest>d__81.MoveNext() in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 167
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.MinioClient.<BucketExistsAsync>d__2.MoveNext() in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/BucketOperations.cs:line 124
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at IntellaLend.MinIOWrapper.ImageMinIOWrapper.CheckFileExists(Int64 loanID) in D:\Prakash\GitHub\ILProduct\IntellaLendBlocks\IntellaLend.MinIOWrapper\MinIOWrapper.cs:line 237
   at IntellaLend.EntityDataHandler.LoanDataAccess.CheckLoanPDFExists(Int64 LoanID) in D:\Prakash\GitHub\ILProduct\IntellaLendAPI\IntellaLend.LoanData\LoanDataAccess.cs:line 1372
   at IntellaLend.CommonServices.LoanService.CheckLoanPDFExists(Int64 LoanID) in D:\Prakash\GitHub\ILProduct\IntellaLendAPI\IntellaLend.Services\LoanService\LoanService.cs:line 105
   at IntellaLendAPI.Controllers.LoanController.CheckLoanPDFExists(LoanRequest loan) in D:\Prakash\GitHub\ILProduct\IntellaLendAPI\IntellaLendAPI\Controllers\LoanController.cs:line 840

Additional Info:

MachineName : MTS0091
TimeStamp : 12/22/2020 3:54:13 PM
FullName : Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
AppDomainName : /LM/W3SVC/2/ROOT-1-132531234307358378
ThreadIdentity : APIResponse
WindowsIdentity : MTS0091\mtsuser


Category: General
EventID: 9000
Priority: 0
Severity: ErrorTitile: Enterprise Library Exception Handling
----------------------------------------
Timestamp: 12/22/2020 9:26:48 PM

Message: HandlingInstanceID: 36bc4dc4-f2be-441a-84e0-62ed7e60b10d
An exception of type 'Minio.Exceptions.ConnectionException' occurred and was caught.
------------------------------------------------------------------------------------
12/22/2020 21:26:48
Type : Minio.Exceptions.ConnectionException, Minio, Version=3.1.13.0, Culture=neutral, PublicKeyToken=348239ebd7debb4c
Message : MinIO API responded with message=Connection error: Unable to connect to the remote server. Status code=0, response=Unable to connect to the remote server, content=
Source : Minio
Help link : 
ServerMessage : Connection error: Unable to connect to the remote server
ServerResponse : RestSharp.RestResponse
Response : 
XmlError : 
Data : System.Collections.ListDictionaryInternal
TargetSite : Void ParseErrorNoContent(RestSharp.IRestResponse)
HResult : -2146233088
Stack Trace :    at Minio.MinioClient.ParseErrorNoContent(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 445
   at Minio.MinioClient.ParseError(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 426
   at Minio.MinioClient.<>c.<.ctor>b__84_0(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 81
   at Minio.MinioClient.HandleIfErrorResponse(IRestResponse response, IEnumerable`1 handlers, DateTime startTime) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 604
   at Minio.MinioClient.<ExecuteTaskCoreAsync>d__91.MoveNext() in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 404
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.BucketRegionCache.<Update>d__9.MoveNext() in /q/.q/sources/minio-dotnet/Minio/BucketRegionCache.cs:line 104
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.MinioClient.<GetRegion>d__80.MoveNext() in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 134
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.MinioClient.<CreateRequest>d__81.MoveNext() in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 167
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.MinioClient.<BucketExistsAsync>d__2.MoveNext() in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/BucketOperations.cs:line 124
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at IntellaLend.MinIOWrapper.ImageMinIOWrapper.CheckFileExists(Int64 loanID) in D:\Prakash\GitHub\ILProduct\IntellaLendBlocks\IntellaLend.MinIOWrapper\MinIOWrapper.cs:line 237
   at IntellaLend.EntityDataHandler.LoanDataAccess.CheckLoanPDFExists(Int64 LoanID) in D:\Prakash\GitHub\ILProduct\IntellaLendAPI\IntellaLend.LoanData\LoanDataAccess.cs:line 1372
   at IntellaLend.CommonServices.LoanService.CheckLoanPDFExists(Int64 LoanID) in D:\Prakash\GitHub\ILProduct\IntellaLendAPI\IntellaLend.Services\LoanService\LoanService.cs:line 105
   at IntellaLendAPI.Controllers.LoanController.CheckLoanPDFExists(LoanRequest loan) in D:\Prakash\GitHub\ILProduct\IntellaLendAPI\IntellaLendAPI\Controllers\LoanController.cs:line 840

Additional Info:

MachineName : MTS0091
TimeStamp : 12/22/2020 3:56:48 PM
FullName : Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
AppDomainName : /LM/W3SVC/2/ROOT-1-132531234307358378
ThreadIdentity : APIResponse
WindowsIdentity : MTS0091\mtsuser


Category: General
EventID: 9000
Priority: 0
Severity: ErrorTitile: Enterprise Library Exception Handling
----------------------------------------
Timestamp: 12/22/2020 9:28:10 PM

Message: HandlingInstanceID: d49bf86a-dea0-4583-ae32-34000e52d913
An exception of type 'Minio.Exceptions.ConnectionException' occurred and was caught.
------------------------------------------------------------------------------------
12/22/2020 21:28:10
Type : Minio.Exceptions.ConnectionException, Minio, Version=3.1.13.0, Culture=neutral, PublicKeyToken=348239ebd7debb4c
Message : MinIO API responded with message=Connection error: Unable to connect to the remote server. Status code=0, response=Unable to connect to the remote server, content=
Source : Minio
Help link : 
ServerMessage : Connection error: Unable to connect to the remote server
ServerResponse : RestSharp.RestResponse
Response : 
XmlError : 
Data : System.Collections.ListDictionaryInternal
TargetSite : Void ParseErrorNoContent(RestSharp.IRestResponse)
HResult : -2146233088
Stack Trace :    at Minio.MinioClient.ParseErrorNoContent(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 445
   at Minio.MinioClient.ParseError(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 426
   at Minio.MinioClient.<>c.<.ctor>b__84_0(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 81
   at Minio.MinioClient.HandleIfErrorResponse(IRestResponse response, IEnumerable`1 handlers, DateTime startTime) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 604
   at Minio.MinioClient.<ExecuteTaskCoreAsync>d__91.MoveNext() in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 404
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.BucketRegionCache.<Update>d__9.MoveNext() in /q/.q/sources/minio-dotnet/Minio/BucketRegionCache.cs:line 104
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.MinioClient.<GetRegion>d__80.MoveNext() in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 134
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.MinioClient.<CreateRequest>d__81.MoveNext() in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 167
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.MinioClient.<BucketExistsAsync>d__2.MoveNext() in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/BucketOperations.cs:line 124
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at IntellaLend.MinIOWrapper.ImageMinIOWrapper.CheckFileExists(Int64 loanID) in D:\Prakash\GitHub\ILProduct\IntellaLendBlocks\IntellaLend.MinIOWrapper\MinIOWrapper.cs:line 237
   at IntellaLend.EntityDataHandler.LoanDataAccess.CheckLoanPDFExists(Int64 LoanID) in D:\Prakash\GitHub\ILProduct\IntellaLendAPI\IntellaLend.LoanData\LoanDataAccess.cs:line 1372
   at IntellaLend.CommonServices.LoanService.CheckLoanPDFExists(Int64 LoanID) in D:\Prakash\GitHub\ILProduct\IntellaLendAPI\IntellaLend.Services\LoanService\LoanService.cs:line 105
   at IntellaLendAPI.Controllers.LoanController.CheckLoanPDFExists(LoanRequest loan) in D:\Prakash\GitHub\ILProduct\IntellaLendAPI\IntellaLendAPI\Controllers\LoanController.cs:line 840

Additional Info:

MachineName : MTS0091
TimeStamp : 12/22/2020 3:58:10 PM
FullName : Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
AppDomainName : /LM/W3SVC/2/ROOT-1-132531234307358378
ThreadIdentity : APIResponse
WindowsIdentity : MTS0091\mtsuser


Category: General
EventID: 9000
Priority: 0
Severity: ErrorTitile: Enterprise Library Exception Handling
----------------------------------------
Timestamp: 12/22/2020 9:29:23 PM

Message: HandlingInstanceID: 28b3bbbd-a64a-46c2-bbc4-84a7fc3d1c48
An exception of type 'Minio.Exceptions.ConnectionException' occurred and was caught.
------------------------------------------------------------------------------------
12/22/2020 21:29:23
Type : Minio.Exceptions.ConnectionException, Minio, Version=3.1.13.0, Culture=neutral, PublicKeyToken=348239ebd7debb4c
Message : MinIO API responded with message=Connection error: Unable to connect to the remote server. Status code=0, response=Unable to connect to the remote server, content=
Source : Minio
Help link : 
ServerMessage : Connection error: Unable to connect to the remote server
ServerResponse : RestSharp.RestResponse
Response : 
XmlError : 
Data : System.Collections.ListDictionaryInternal
TargetSite : Void ParseErrorNoContent(RestSharp.IRestResponse)
HResult : -2146233088
Stack Trace :    at Minio.MinioClient.ParseErrorNoContent(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 445
   at Minio.MinioClient.ParseError(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 426
   at Minio.MinioClient.<>c.<.ctor>b__84_0(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 81
   at Minio.MinioClient.HandleIfErrorResponse(IRestResponse response, IEnumerable`1 handlers, DateTime startTime) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 604
   at Minio.MinioClient.<ExecuteTaskCoreAsync>d__91.MoveNext() in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 404
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.BucketRegionCache.<Update>d__9.MoveNext() in /q/.q/sources/minio-dotnet/Minio/BucketRegionCache.cs:line 104
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.MinioClient.<GetRegion>d__80.MoveNext() in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 134
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.MinioClient.<CreateRequest>d__81.MoveNext() in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 167
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.MinioClient.<BucketExistsAsync>d__2.MoveNext() in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/BucketOperations.cs:line 124
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at IntellaLend.MinIOWrapper.ImageMinIOWrapper.CheckFileExists(Int64 loanID) in D:\Prakash\GitHub\ILProduct\IntellaLendBlocks\IntellaLend.MinIOWrapper\MinIOWrapper.cs:line 237
   at IntellaLend.EntityDataHandler.LoanDataAccess.CheckLoanPDFExists(Int64 LoanID) in D:\Prakash\GitHub\ILProduct\IntellaLendAPI\IntellaLend.LoanData\LoanDataAccess.cs:line 1372
   at IntellaLend.CommonServices.LoanService.CheckLoanPDFExists(Int64 LoanID) in D:\Prakash\GitHub\ILProduct\IntellaLendAPI\IntellaLend.Services\LoanService\LoanService.cs:line 105
   at IntellaLendAPI.Controllers.LoanController.CheckLoanPDFExists(LoanRequest loan) in D:\Prakash\GitHub\ILProduct\IntellaLendAPI\IntellaLendAPI\Controllers\LoanController.cs:line 840

Additional Info:

MachineName : MTS0091
TimeStamp : 12/22/2020 3:59:23 PM
FullName : Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
AppDomainName : /LM/W3SVC/2/ROOT-1-132531234307358378
ThreadIdentity : APIResponse
WindowsIdentity : MTS0091\mtsuser


Category: General
EventID: 9000
Priority: 0
Severity: ErrorTitile: Enterprise Library Exception Handling
----------------------------------------
Timestamp: 12/22/2020 9:30:08 PM

Message: HandlingInstanceID: 8144ec2b-21d5-402f-92a2-274059e630a1
An exception of type 'Minio.Exceptions.ConnectionException' occurred and was caught.
------------------------------------------------------------------------------------
12/22/2020 21:30:08
Type : Minio.Exceptions.ConnectionException, Minio, Version=3.1.13.0, Culture=neutral, PublicKeyToken=348239ebd7debb4c
Message : MinIO API responded with message=Connection error: Unable to connect to the remote server. Status code=0, response=Unable to connect to the remote server, content=
Source : Minio
Help link : 
ServerMessage : Connection error: Unable to connect to the remote server
ServerResponse : RestSharp.RestResponse
Response : 
XmlError : 
Data : System.Collections.ListDictionaryInternal
TargetSite : Void ParseErrorNoContent(RestSharp.IRestResponse)
HResult : -2146233088
Stack Trace :    at Minio.MinioClient.ParseErrorNoContent(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 445
   at Minio.MinioClient.ParseError(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 426
   at Minio.MinioClient.<>c.<.ctor>b__84_0(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 81
   at Minio.MinioClient.HandleIfErrorResponse(IRestResponse response, IEnumerable`1 handlers, DateTime startTime) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 604
   at Minio.MinioClient.<ExecuteTaskCoreAsync>d__91.MoveNext() in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 404
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.BucketRegionCache.<Update>d__9.MoveNext() in /q/.q/sources/minio-dotnet/Minio/BucketRegionCache.cs:line 104
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.MinioClient.<GetRegion>d__80.MoveNext() in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 134
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.MinioClient.<CreateRequest>d__81.MoveNext() in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 167
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.MinioClient.<BucketExistsAsync>d__2.MoveNext() in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/BucketOperations.cs:line 124
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at IntellaLend.MinIOWrapper.ImageMinIOWrapper.CheckFileExists(Int64 loanID) in D:\Prakash\GitHub\ILProduct\IntellaLendBlocks\IntellaLend.MinIOWrapper\MinIOWrapper.cs:line 237
   at IntellaLend.EntityDataHandler.LoanDataAccess.CheckLoanPDFExists(Int64 LoanID) in D:\Prakash\GitHub\ILProduct\IntellaLendAPI\IntellaLend.LoanData\LoanDataAccess.cs:line 1372
   at IntellaLend.CommonServices.LoanService.CheckLoanPDFExists(Int64 LoanID) in D:\Prakash\GitHub\ILProduct\IntellaLendAPI\IntellaLend.Services\LoanService\LoanService.cs:line 105
   at IntellaLendAPI.Controllers.LoanController.CheckLoanPDFExists(LoanRequest loan) in D:\Prakash\GitHub\ILProduct\IntellaLendAPI\IntellaLendAPI\Controllers\LoanController.cs:line 840

Additional Info:

MachineName : MTS0091
TimeStamp : 12/22/2020 4:00:08 PM
FullName : Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
AppDomainName : /LM/W3SVC/2/ROOT-1-132531234307358378
ThreadIdentity : APIResponse
WindowsIdentity : MTS0091\mtsuser


Category: General
EventID: 9000
Priority: 0
Severity: ErrorTitile: Enterprise Library Exception Handling
----------------------------------------
Timestamp: 12/22/2020 9:31:39 PM

Message: HandlingInstanceID: d222317c-3867-41a1-b7fe-60f4fc281b79
An exception of type 'Minio.Exceptions.ConnectionException' occurred and was caught.
------------------------------------------------------------------------------------
12/22/2020 21:31:39
Type : Minio.Exceptions.ConnectionException, Minio, Version=3.1.13.0, Culture=neutral, PublicKeyToken=348239ebd7debb4c
Message : MinIO API responded with message=Connection error: Unable to connect to the remote server. Status code=0, response=Unable to connect to the remote server, content=
Source : Minio
Help link : 
ServerMessage : Connection error: Unable to connect to the remote server
ServerResponse : RestSharp.RestResponse
Response : 
XmlError : 
Data : System.Collections.ListDictionaryInternal
TargetSite : Void ParseErrorNoContent(RestSharp.IRestResponse)
HResult : -2146233088
Stack Trace :    at Minio.MinioClient.ParseErrorNoContent(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 445
   at Minio.MinioClient.ParseError(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 426
   at Minio.MinioClient.<>c.<.ctor>b__84_0(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 81
   at Minio.MinioClient.HandleIfErrorResponse(IRestResponse response, IEnumerable`1 handlers, DateTime startTime) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 604
   at Minio.MinioClient.<ExecuteTaskCoreAsync>d__91.MoveNext() in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 404
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.BucketRegionCache.<Update>d__9.MoveNext() in /q/.q/sources/minio-dotnet/Minio/BucketRegionCache.cs:line 104
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.MinioClient.<GetRegion>d__80.MoveNext() in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 134
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.MinioClient.<CreateRequest>d__81.MoveNext() in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 167
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Minio.MinioClient.<BucketExistsAsync>d__2.MoveNext() in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/BucketOperations.cs:line 124
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at IntellaLend.MinIOWrapper.ImageMinIOWrapper.CheckFileExists(Int64 loanID) in D:\Prakash\GitHub\ILProduct\IntellaLendBlocks\IntellaLend.MinIOWrapper\MinIOWrapper.cs:line 237
   at IntellaLend.EntityDataHandler.LoanDataAccess.CheckLoanPDFExists(Int64 LoanID) in D:\Prakash\GitHub\ILProduct\IntellaLendAPI\IntellaLend.LoanData\LoanDataAccess.cs:line 1372
   at IntellaLend.CommonServices.LoanService.CheckLoanPDFExists(Int64 LoanID) in D:\Prakash\GitHub\ILProduct\IntellaLendAPI\IntellaLend.Services\LoanService\LoanService.cs:line 105
   at IntellaLendAPI.Controllers.LoanController.CheckLoanPDFExists(LoanRequest loan) in D:\Prakash\GitHub\ILProduct\IntellaLendAPI\IntellaLendAPI\Controllers\LoanController.cs:line 840

Additional Info:

MachineName : MTS0091
TimeStamp : 12/22/2020 4:01:39 PM
FullName : Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
AppDomainName : /LM/W3SVC/2/ROOT-1-132531234307358378
ThreadIdentity : APIResponse
WindowsIdentity : MTS0091\mtsuser


Category: General
EventID: 9000
Priority: 0
Severity: ErrorTitile: Enterprise Library Exception Handling
----------------------------------------
